//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSunLiteTest.ADO2Transaction
{
    using System;
    using NSun;
    using NSun.Data;


    [System.SerializableAttribute()]
    [NSun.Data.TableAttribute("USERS")]
    public partial class UsersIdEntity : NSun.Data.BaseEntity
    {
        public static NSun.Data.QueryColumn _id = new NSun.Data.QueryColumn("USERS.ID", System.Data.DbType.Int64);

        private long id;

        [NSun.Data.PrimaryKeyAttribute(true)]
        public long Id
        {
            get
            {
                return id;
            }
            set
            {
                id = value;
            }
        }
    }

    [System.SerializableAttribute()]
    public partial class UsersEN : UsersIdEntity
    {

        public static NSun.Data.QueryColumn _name = new NSun.Data.QueryColumn("USERS.NAME", System.Data.DbType.String);

        private string name;

        public string Name
        {
            get
            {
                return name;
            }
            set
            {
                name = value;
            }
        }

        public static NSun.Data.QueryColumn _pass = new NSun.Data.QueryColumn("USERS.PASS", System.Data.DbType.String);

        private string pass;

        public string Pass
        {
            get
            {
                return pass;
            }
            set
            {
                pass = value;
            }
        }

        public static NSun.Data.QueryColumn _logintime = new NSun.Data.QueryColumn("USERS.LOGINTIME", System.Data.DbType.DateTime);

        private System.Nullable<System.DateTime> logintime;

        public System.Nullable<System.DateTime> Logintime
        {
            get
            {
                return logintime;
            }
            set
            {
                logintime = value;
            }
        }
    }



    
    [System.SerializableAttribute()]
    [NSun.Data.TableAttribute("USERS")]
    public partial class UsersEntity : NSun.Data.BaseEntity
    {
        
        public static NSun.Data.QueryColumn _id = new NSun.Data.QueryColumn("USERS.ID", System.Data.DbType.Int64);
        
        private long id;
        
        [NSun.Data.PrimaryKeyAttribute(true)]
        public long Id
        {
            get
            {
                return id;
            }
            set
            {
                id = value;
            }
        }
        
        public static NSun.Data.QueryColumn _name = new NSun.Data.QueryColumn("USERS.NAME", System.Data.DbType.String);
        
        private string name;
        
        public string Name
        {
            get
            {
                return name;
            }
            set
            {
                name = value;
            }
        }
        
        public static NSun.Data.QueryColumn _pass = new NSun.Data.QueryColumn("USERS.PASS", System.Data.DbType.String);
        
        private string pass;
        
        public string Pass
        {
            get
            {
                return pass;
            }
            set
            {
                pass = value;
            }
        }
        
        public static NSun.Data.QueryColumn _logintime = new NSun.Data.QueryColumn("USERS.LOGINTIME", System.Data.DbType.DateTime);
        
        private System.Nullable<System.DateTime> logintime;
        
        public System.Nullable<System.DateTime> Logintime
        {
            get
            {
                return logintime;
            }
            set
            {
                logintime = value;
            }
        }
    }
}
