//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5446
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSunLiteTest
{
    using System;
    using NSun;
    using NSun.Data;
    
    
    [System.SerializableAttribute()]
    [NSun.Data.TableAttribute("HZ_QYHZNR")]
    public partial class Hz_qyhznr : NSun.Data.BaseEntity
    {
        
        public static NSun.Data.QueryColumn _ID = new NSun.Data.QueryColumn("HZ_QYHZNR.ID", System.Data.DbType.Int32);
        
        private int iD;
        
        [NSun.Data.PrimaryKeyAttribute(true)]
        public int ID
        {
            get
            {
                return iD;
            }
            set
            {
                iD = value;
            }
        }
        
        public static NSun.Data.QueryColumn _QYMC = new NSun.Data.QueryColumn("HZ_QYHZNR.QYMC", System.Data.DbType.String);
        
        private string qYMC;
        
        public string QYMC
        {
            get
            {
                return qYMC;
            }
            set
            {
                qYMC = value;
            }
        }
        
        public static NSun.Data.QueryColumn _DH = new NSun.Data.QueryColumn("HZ_QYHZNR.DH", System.Data.DbType.String);
        
        private string dH;
        
        public string DH
        {
            get
            {
                return dH;
            }
            set
            {
                dH = value;
            }
        }
        
        public static NSun.Data.QueryColumn _ZS = new NSun.Data.QueryColumn("HZ_QYHZNR.ZS", System.Data.DbType.String);
        
        private string zS;
        
        public string ZS
        {
            get
            {
                return zS;
            }
            set
            {
                zS = value;
            }
        }
        
        public static NSun.Data.QueryColumn _JYFW = new NSun.Data.QueryColumn("HZ_QYHZNR.JYFW", System.Data.DbType.String);
        
        private string jYFW;
        
        public string JYFW
        {
            get
            {
                return jYFW;
            }
            set
            {
                jYFW = value;
            }
        }
        
        public static NSun.Data.QueryColumn _FDDBR = new NSun.Data.QueryColumn("HZ_QYHZNR.FDDBR", System.Data.DbType.String);
        
        private string fDDBR;
        
        public string FDDBR
        {
            get
            {
                return fDDBR;
            }
            set
            {
                fDDBR = value;
            }
        }
        
        public static NSun.Data.QueryColumn _JYQSRQ = new NSun.Data.QueryColumn("HZ_QYHZNR.JYQSRQ", System.Data.DbType.String);
        
        private string jYQSRQ;
        
        public string JYQSRQ
        {
            get
            {
                return jYQSRQ;
            }
            set
            {
                jYQSRQ = value;
            }
        }
        
        public static NSun.Data.QueryColumn _JYJZRQ = new NSun.Data.QueryColumn("HZ_QYHZNR.JYJZRQ", System.Data.DbType.String);
        
        private string jYJZRQ;
        
        public string JYJZRQ
        {
            get
            {
                return jYJZRQ;
            }
            set
            {
                jYJZRQ = value;
            }
        }
        
        public static NSun.Data.QueryColumn _ZCZB = new NSun.Data.QueryColumn("HZ_QYHZNR.ZCZB", System.Data.DbType.Int32);
        
        private System.Nullable<int> zCZB;
        
        public System.Nullable<int> ZCZB
        {
            get
            {
                return zCZB;
            }
            set
            {
                zCZB = value;
            }
        }
    }
}
