//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClient.ServiceStudent {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyValuePairOfstringConditionJnTejB4J", Namespace="http://schemas.datacontract.org/2004/07/System.Collections.Generic")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.ParameterEqualsCondition))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.QueryCriteria))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.QueryType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.ExpressionClip))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.Expression))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.Assignment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.NullExpression))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.ExpressionCollection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.ParameterExpression))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.SprocParameterDirection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.QueryColumn))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.VersionQueryColumn))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.IdQueryColumn))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.RelationQueryColumn))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.BaseEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.BaseEntityRefObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.SprocEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.StoredProcedureSection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<NSun.Data.ParameterEqualsCondition>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.SelectSqlSection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.FromClip))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.InsertSqlSection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<NSun.Data.Assignment>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.UpdateSqlSection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.DeleteSqlSection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.CustomSqlSection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.SubQuery))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.OrderByClip))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<NSun.Data.ExpressionClip>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<NSun.Data.ConditionAndOr>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.ConditionAndOr))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<NSun.Data.Condition>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.ExpressionOperator))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, WCFClient.ServiceStudent.KeyValuePairOfstringConditionJnTejB4J>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<NSun.Data.ExpressionClip, bool>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFClient.ServiceStudent.MarshalByRefObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<NSun.Data.JoinType>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.JoinType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFClient.ServiceStudent.KeyValuePairOfExpressionClipbooleanrIZo_Semb))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<RemotingModel.StudentRemotingModel>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RemotingModel.StudentRemotingModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RemotingModel.StudentInfoRemotingModel))]
    public partial struct KeyValuePairOfstringConditionJnTejB4J : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string keyField;
        
        private NSun.Data.Condition valueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                if ((object.ReferenceEquals(this.keyField, value) != true)) {
                    this.keyField = value;
                    this.RaisePropertyChanged("key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public NSun.Data.Condition value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarshalByRefObject", Namespace="http://schemas.datacontract.org/2004/07/System")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.BaseEntityRefObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RemotingModel.StudentRemotingModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.QueryCriteria))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.QueryType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.Condition))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.ExpressionClip))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.Expression))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.Assignment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.ParameterEqualsCondition))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.NullExpression))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.ExpressionCollection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.ParameterExpression))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.SprocParameterDirection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.QueryColumn))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.VersionQueryColumn))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.IdQueryColumn))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.RelationQueryColumn))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.BaseEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.SprocEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.StoredProcedureSection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<NSun.Data.ParameterEqualsCondition>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.SelectSqlSection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.FromClip))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.InsertSqlSection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<NSun.Data.Assignment>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.UpdateSqlSection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.DeleteSqlSection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.CustomSqlSection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.SubQuery))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.OrderByClip))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<NSun.Data.ExpressionClip>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<NSun.Data.ConditionAndOr>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.ConditionAndOr))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<NSun.Data.Condition>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.ExpressionOperator))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, WCFClient.ServiceStudent.KeyValuePairOfstringConditionJnTejB4J>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<NSun.Data.ExpressionClip, bool>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<NSun.Data.JoinType>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.JoinType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFClient.ServiceStudent.KeyValuePairOfstringConditionJnTejB4J))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFClient.ServiceStudent.KeyValuePairOfExpressionClipbooleanrIZo_Semb))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<RemotingModel.StudentRemotingModel>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RemotingModel.StudentInfoRemotingModel))]
    public partial class MarshalByRefObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private object @__identityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object @__identity {
            get {
                return this.@__identityField;
            }
            set {
                if ((object.ReferenceEquals(this.@__identityField, value) != true)) {
                    this.@__identityField = value;
                    this.RaisePropertyChanged("__identity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyValuePairOfExpressionClipbooleanrIZo_Semb", Namespace="http://schemas.datacontract.org/2004/07/System.Collections.Generic")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.ParameterExpression))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.QueryColumn))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.VersionQueryColumn))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.IdQueryColumn))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.RelationQueryColumn))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.SubQuery))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.Condition))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NSun.Data.ParameterEqualsCondition))]
    public partial struct KeyValuePairOfExpressionClipbooleanrIZo_Semb : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private NSun.Data.ExpressionClip keyField;
        
        private bool valueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public NSun.Data.ExpressionClip key {
            get {
                return this.keyField;
            }
            set {
                if ((object.ReferenceEquals(this.keyField, value) != true)) {
                    this.keyField = value;
                    this.RaisePropertyChanged("key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool value {
            get {
                return this.valueField;
            }
            set {
                if ((this.valueField.Equals(value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceStudent.IStudentService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IStudentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudent", ReplyAction="http://tempuri.org/IStudentService/GetStudentResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NSun.Data.SprocEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NSun.Data.StoredProcedureSection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NSun.Data.SelectSqlSection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NSun.Data.InsertSqlSection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NSun.Data.UpdateSqlSection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NSun.Data.DeleteSqlSection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NSun.Data.CustomSqlSection))]
        System.Collections.Generic.List<RemotingModel.StudentRemotingModel> GetStudent(NSun.Data.QueryCriteria criteria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/Save", ReplyAction="http://tempuri.org/IStudentService/SaveResponse")]
        int Save(RemotingModel.StudentRemotingModel student);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentServiceChannel : WCFClient.ServiceStudent.IStudentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentServiceClient : System.ServiceModel.ClientBase<WCFClient.ServiceStudent.IStudentService>, WCFClient.ServiceStudent.IStudentService {
        
        public StudentServiceClient() {
        }
        
        public StudentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<RemotingModel.StudentRemotingModel> GetStudent(NSun.Data.QueryCriteria criteria) {
            return base.Channel.GetStudent(criteria);
        }
        
        public int Save(RemotingModel.StudentRemotingModel student) {
            return base.Channel.Save(student);
        }
    }
}
