//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySql8.Entity
{
    using System;
    using NSun;
    using NSun.Data;
    using NSun.Data.Collection;
    
    
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.DataContractAttribute()]
    [NSun.Data.TableAttribute("KKPASS")]
    public class Kkpass : NSun.Data.BaseEntityRefObject
    {
        
        static Kkpass()
        {
            _XH = new NSun.Data.IdQueryColumn("KKPASS.XH", System.Data.DbType.String);
            _PZSJ = new NSun.Data.QueryColumn("KKPASS.PZSJ", System.Data.DbType.String);
            _KKID = new NSun.Data.QueryColumn("KKPASS.KKID", System.Data.DbType.String);
            _FX = new NSun.Data.QueryColumn("KKPASS.FX", System.Data.DbType.String);
            _HPZL = new NSun.Data.QueryColumn("KKPASS.HPZL", System.Data.DbType.String);
            _CDH = new NSun.Data.QueryColumn("KKPASS.CDH", System.Data.DbType.String);
            _PASSXH = new NSun.Data.QueryColumn("KKPASS.PASSXH", System.Data.DbType.String);
            _PASSID = new NSun.Data.IdQueryColumn("KKPASS.PASSID", System.Data.DbType.String);
        }
        
        private string xH;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XH
        {
            get
            {
                return xH;
            }
            set
            {
                xH = value;
            }
        }
        
        public static NSun.Data.IdQueryColumn _XH;
        
        private string pZSJ;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PZSJ
        {
            get
            {
                return pZSJ;
            }
            set
            {
                pZSJ = value;
            }
        }
        
        public static NSun.Data.QueryColumn _PZSJ;
        
        private string kKID;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KKID
        {
            get
            {
                return kKID;
            }
            set
            {
                kKID = value;
            }
        }
        
        public static NSun.Data.QueryColumn _KKID;
        
        private string fX;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FX
        {
            get
            {
                return fX;
            }
            set
            {
                fX = value;
            }
        }
        
        public static NSun.Data.QueryColumn _FX;
        
        private string hPZL;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HPZL
        {
            get
            {
                return hPZL;
            }
            set
            {
                hPZL = value;
            }
        }
        
        public static NSun.Data.QueryColumn _HPZL;
        
        private string cDH;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CDH
        {
            get
            {
                return cDH;
            }
            set
            {
                cDH = value;
            }
        }
        
        public static NSun.Data.QueryColumn _CDH;
        
        private string pASSXH;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PASSXH
        {
            get
            {
                return pASSXH;
            }
            set
            {
                pASSXH = value;
            }
        }
        
        public static NSun.Data.QueryColumn _PASSXH;
        
        private string pASSID;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PASSID
        {
            get
            {
                return pASSID;
            }
            set
            {
                pASSID = value;
            }
        }
        
        public static NSun.Data.IdQueryColumn _PASSID;
    }
}
