using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Reflection;

namespace NSun.Data
{
    public class TableSchema
    {
        public QueryColumn IdentyColumn;
        public MemberInfo IdentyFieldMemberInfo;
        public bool IsIdentyFieldAutoGenerated;

        private string tableName;

        public string TableName
        {
            get
            {
                if (string.IsNullOrEmpty(tableName))
                {
                    tableName = EntityInfo.GetTableName();
                }
                return tableName;
            }
        }

        public IBaseEntity EntityInfo;
        public object MappingInfo;

        public ActiveRecordFieldList CreateFields;
        public ActiveRecordFieldList UpdateFields;

        public PropertyInfo[] ValuePropertys;
        public FieldInfo[] FindFields;

        //所有查询列
        public Dictionary<string, QueryColumn> QueryColumns =
            new Dictionary<string, QueryColumn>();

        //乐观锁版本列
        public Dictionary<string, QueryColumn> OptimisticLocking =
            new Dictionary<string, QueryColumn>();

        //关系列
        public Dictionary<string, RelationQueryColumn> RelationColumn =
             new Dictionary<string, RelationQueryColumn>();
    }
     
}
