//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSunLiteTest.ADO2Transaction
{
    using System;
    using NSun;
    using NSun.Data;
    
    
    [System.SerializableAttribute()]
    [NSun.Data.TableAttribute("SELECTITEM")]
    public partial class SelectItemEntity : NSun.Data.BaseEntity
    {
        
        public static NSun.Data.QueryColumn _id = new NSun.Data.QueryColumn("SELECTITEM.ID", System.Data.DbType.Int32);
        
        private int id;
        
        [NSun.Data.PrimaryKeyAttribute(true)]
        public int Id
        {
            get
            {
                return id;
            }
            set
            {
                id = value;
            }
        }
        
        public static NSun.Data.QueryColumn _titleid = new NSun.Data.QueryColumn("SELECTITEM.TITLEID", System.Data.DbType.Int32);
        
        private System.Nullable<int> titleid;
        
        public System.Nullable<int> Titleid
        {
            get
            {
                return titleid;
            }
            set
            {
                titleid = value;
            }
        }
        
        public static NSun.Data.QueryColumn _selectnum = new NSun.Data.QueryColumn("SELECTITEM.SELECTNUM", System.Data.DbType.String);
        
        private string selectnum;
        
        public string Selectnum
        {
            get
            {
                return selectnum;
            }
            set
            {
                selectnum = value;
            }
        }
        
        public static NSun.Data.QueryColumn _selectcontext = new NSun.Data.QueryColumn("SELECTITEM.SELECTCONTEXT", System.Data.DbType.String);
        
        private string selectcontext;
        
        public string Selectcontext
        {
            get
            {
                return selectcontext;
            }
            set
            {
                selectcontext = value;
            }
        }
    }
}
