//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemotingModel
{
    using System;
    using NSun;
    using NSun.Data;
    using NSun.Data.Collection;


    [NSun.Data.TableAttribute("BOOK")]
    public class BookRemotingModelTable
    {

        static BookRemotingModelTable()
        {
            _id = new NSun.Data.IdQueryColumn("BOOK.ID", System.Data.DbType.Int32, true);
            _name = new NSun.Data.QueryColumn("BOOK.NAME", System.Data.DbType.String);
            _price = new NSun.Data.QueryColumn("BOOK.PRICE", System.Data.DbType.Decimal);
        }

        public static NSun.Data.IdQueryColumn _id;

        public static NSun.Data.QueryColumn _name;

        public static NSun.Data.QueryColumn _price;


    }
}
