//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemotingModel
{
    using System;
    using NSun;
    using NSun.Data;
    using NSun.Data.Collection;
    
    
    [NSun.Data.TableAttribute("STUDENTINFO")]
    public class StudentInfoRemotingModelTable
    {
        
        static StudentInfoRemotingModelTable()
        {
            _id = new NSun.Data.IdQueryColumn("STUDENTINFO.ID", System.Data.DbType.Int32, true);
            _studentid = new NSun.Data.QueryColumn("STUDENTINFO.STUDENTID", System.Data.DbType.Int32);
            _code = new NSun.Data.QueryColumn("STUDENTINFO.CODE", System.Data.DbType.String);
            _address = new NSun.Data.QueryColumn("STUDENTINFO.ADDRESS", System.Data.DbType.String);
        }
        
        public static NSun.Data.IdQueryColumn _id;
        
        public static NSun.Data.QueryColumn _studentid;
        
        public static NSun.Data.QueryColumn _code;
        
        public static NSun.Data.QueryColumn _address;
    }
}
