//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemotingModel
{
    using System;
    using NSun;
    using NSun.Data;
    using NSun.Data.Collection;
    
    
    [NSun.Data.TableAttribute("STUDENT")]
    public class StudentRemotingModelTable
    {
        
        static StudentRemotingModelTable()
        {
            _id = new NSun.Data.IdQueryColumn("STUDENT.ID", System.Data.DbType.Int32, true);
            _name = new NSun.Data.QueryColumn("STUDENT.NAME", System.Data.DbType.String);
            _pass = new NSun.Data.QueryColumn("STUDENT.PASS", System.Data.DbType.String);
            _birthday = new NSun.Data.QueryColumn("STUDENT.BIRTHDAY", System.Data.DbType.DateTime);
            _age = new NSun.Data.QueryColumn("STUDENT.AGE", System.Data.DbType.Int32);
            _classid = new NSun.Data.QueryColumn("STUDENT.CLASSID", System.Data.DbType.Int32);
            _stamp = new NSun.Data.QueryColumn("STUDENT.STAMP", System.Data.DbType.Binary);
            _studentinfo = new RelationQueryColumn(_id, typeof (StudentInfoRemotingModelTable),
                                                   StudentInfoRemotingModelTable._studentid, RelationType.OneToOne);
        }
        
        public static NSun.Data.IdQueryColumn _id;
        
        public static NSun.Data.QueryColumn _name;
        
        public static NSun.Data.QueryColumn _pass;
        
        public static NSun.Data.QueryColumn _birthday;
        
        public static NSun.Data.QueryColumn _age;
        
        public static NSun.Data.QueryColumn _classid;
        
        public static NSun.Data.QueryColumn _stamp;

        public static NSun.Data.RelationQueryColumn _studentinfo;
    }
}
