//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSunLiteTest
{
    using System;
    using NSun.Data;
    
    
    [System.SerializableAttribute()]
    [NSun.Data.ProcedureAttribute("ADDUSERS")]
    public partial class AddusersSproc : NSun.Data.SprocEntity
    {
        
        private int rETURN_VALUE;
        
        [NSun.Data.ReturnParameterAttribute("RETURN_VALUE", System.Data.DbType.Int32, 0)]
        public int RETURN_VALUE
        {
            get
            {
                return rETURN_VALUE;
            }
            set
            {
                rETURN_VALUE = value;
            }
        }
        
        private string name;
        
        [NSun.Data.InputParameterAttribute("name", System.Data.DbType.AnsiString)]
        public string Name
        {
            get
            {
                return name;
            }
            set
            {
                name = value;
            }
        }
        
        private string pass;
        
        [NSun.Data.InputParameterAttribute("pass", System.Data.DbType.AnsiString)]
        public string Pass
        {
            get
            {
                return pass;
            }
            set
            {
                pass = value;
            }
        }
    }
}
