//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSunLiteTest
{
    using System;
    using NSun.Data;
    
    
    [System.SerializableAttribute()]
    [NSun.Data.TableAttribute("PHONE")]
    public partial class PhoneEntity : NSun.Data.BaseEntity
    {
        
        public static NSun.Data.QueryColumn _id = new NSun.Data.QueryColumn("PHONE.ID", System.Data.DbType.Int32);
        
        private int id;
        
        [NSun.Data.PrimaryKeyAttribute(true)]
        public int Id
        {
            get
            {
                return id;
            }
            set
            {
                id = value;
            }
        }
        
        public static NSun.Data.QueryColumn _name = new NSun.Data.QueryColumn("PHONE.NAME", System.Data.DbType.Int32);
        
        private System.Nullable<int> name;
        
        public System.Nullable<int> Name
        {
            get
            {
                return name;
            }
            set
            {
                name = value;
            }
        }
    }
}
