//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSunLiteTest
{
    using System;
    using NSun.Data;
    
    
    [System.SerializableAttribute()]
    [NSun.Data.TableAttribute("VIEW_PHONE")]
    public partial class View_phoneEntity : NSun.Data.BaseEntity
    {
        
        public static NSun.Data.QueryColumn _id = new NSun.Data.QueryColumn("VIEW_PHONE.ID", System.Data.DbType.Int32);
        
        private int id;
        
        [NSun.Data.PrimaryKeyAttribute()]
        public int Id
        {
            get
            {
                return id;
            }
            set
            {
                id = value;
            }
        }
        
        public static NSun.Data.QueryColumn _name = new NSun.Data.QueryColumn("VIEW_PHONE.NAME", System.Data.DbType.Int32);
        
        private System.Nullable<int> name;
        
        public System.Nullable<int> Name
        {
            get
            {
                return name;
            }
            set
            {
                name = value;
            }
        }
        
        public static NSun.Data.QueryColumn _Expr1 = new NSun.Data.QueryColumn("VIEW_PHONE.EXPR1", System.Data.DbType.String);
        
        private string expr1;
        
        public string Expr1
        {
            get
            {
                return expr1;
            }
            set
            {
                expr1 = value;
            }
        }
        
        public static NSun.Data.QueryColumn _schoolid = new NSun.Data.QueryColumn("VIEW_PHONE.SCHOOLID", System.Data.DbType.Int32);
        
        private System.Nullable<int> schoolid;
        
        public System.Nullable<int> Schoolid
        {
            get
            {
                return schoolid;
            }
            set
            {
                schoolid = value;
            }
        }
    }
}
