//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemotingModel
{
    using System;
    using NSun;
    using NSun.Data;
    using NSun.Data.Collection;
    
    
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.DataContractAttribute()]
    [NSun.Data.TableMappingAttribute("RemotingModel,RemotingModel.StudentRemotingModelTable")]
    public class StudentRemotingModel : NSun.Data.BaseEntityRefObject
    {
        
        private int id;
        
        [System.Runtime.Serialization.DataMember]
        public int Id
        {
            get
            {
                return id;
            }
            set
            {
                id = value;
            }
        }
        
        private string name;

        [System.Runtime.Serialization.DataMember]
        public string Name
        {
            get
            {
                return name;
            }
            set
            {
                name = value;
            }
        }
        
        private string pass;

        [System.Runtime.Serialization.DataMember]
        public string Pass
        {
            get
            {
                return pass;
            }
            set
            {
                pass = value;
            }
        }
        
        private System.Nullable<System.DateTime> birthday;

        [System.Runtime.Serialization.DataMember]
        public System.Nullable<System.DateTime> Birthday
        {
            get
            {
                return birthday;
            }
            set
            {
                birthday = value;
            }
        }
        
        private System.Nullable<int> age;

        [System.Runtime.Serialization.DataMember]
        public System.Nullable<int> Age
        {
            get
            {
                return age;
            }
            set
            {
                age = value;
            }
        }
        
        private System.Nullable<int> classid;

        [System.Runtime.Serialization.DataMember]
        public System.Nullable<int> Classid
        {
            get
            {
                return classid;
            }
            set
            {
                classid = value;
            }
        }
        
        private byte[] stamp;

        [System.Runtime.Serialization.DataMember]
        public byte[] Stamp
        {
            get
            {
                return stamp;
            }
            set
            {
                stamp = value;
            }
        }

        private StudentInfoRemotingModel studentInfo;

        [System.Runtime.Serialization.DataMember]
        public StudentInfoRemotingModel StudentInfo
        {
            get { return studentInfo; }
            set { studentInfo = value; }
        }
    }
}
