//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simple
{
    using System;
    using NSun;
    using NSun.Data;
    using NSun.Data.Collection;
    
    
    [NSun.Data.TableAttribute("TEACHER")]
    public class TeacherTable
    {
        
        static TeacherTable()
        {
            _id = new NSun.Data.IdQueryColumn("TEACHER.ID", System.Data.DbType.Int32, true);
            _name = new NSun.Data.QueryColumn("TEACHER.NAME", System.Data.DbType.String);
            _classlist = new RelationQueryColumn(_id, typeof(RelationteacherclassTable), typeof(ClassTable),
                                             RelationteacherclassTable._teacherid, //MAPPING
                                             ClassTable._id, //MAPPINGID
                                             RelationteacherclassTable._classid, //OutMaPPING 
                                             RelationType.ManyToMany);
        }
        
        public static NSun.Data.IdQueryColumn _id;
        
        public static NSun.Data.QueryColumn _name;

        private static RelationQueryColumn _classlist;
    }
}
