//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simple
{
    using System;
    using NSun;
    using NSun.Data;
    using NSun.Data.Collection;
    
    
    [NSun.Data.TableAttribute("STUDENT")]
    public class StudentTable
    {
        
        static StudentTable()
        {
            _id = new NSun.Data.IdQueryColumn("STUDENT.ID", System.Data.DbType.Int32, true);
            _name = new NSun.Data.QueryColumn("STUDENT.NAME", System.Data.DbType.String);
            _age = new NSun.Data.QueryColumn("STUDENT.AGE", System.Data.DbType.Int32);
            _classid = new NSun.Data.QueryColumn("STUDENT.CLASSID", System.Data.DbType.Int32);

            _classinfo = new RelationQueryColumn(_classid, typeof (ClassEntity), ClassTable._id, RelationType.ManyToOne);
        }
        
        public static NSun.Data.IdQueryColumn _id;
        
        public static NSun.Data.QueryColumn _name;
        
        public static NSun.Data.QueryColumn _age;

        public static NSun.Data.QueryColumn _classid;

        public static NSun.Data.RelationQueryColumn _classinfo;
    }
}
